use_frameworks!

platform :ios, '11.0'

target 'JBOssUtil_Example' do
  pod 'JBOssUtil', :path => '../'

  target 'JBOssUtil_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # Needed for building for simulator on M1 Macs
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
